# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRna' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRna
  pod 'Moya'
  pod 'SwiftKeychainWrapper'
  pod 'SwiftyJSON'
  pod 'RxSwift'
  pod 'DropDown'

  target 'QRnaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QRnaUITests' do
    # Pods for testing
  end

end
